### ISSUE TITLE
Buderus TC100

### ISSUE THREAD

**Issue by Salvora** [robertklep/homebridge-nefit-easy#29]
Hello,
I tried to use this plugin with Buderus TC100.
It looked like same device with bosch backend. But I couldn't manage to get it work.
Is there a way to do that or not supported at all?

**Comment by robertklep** [comment]
Are you getting any errors? To make testing easier, there's also a [command line tool](https://github.com/robertklep/nefit-easy-cli) that can be used to retrieve information from the thermostat.

**Comment by Salvora** [comment]
I am not getting any debug messages on the console. I will try the command tool to check.

**Comment by robertklep** [comment]
With the command line tool you can get a lot of debugging info when you run it like this:
```
$ env DEBUG=* easy --serial=XXX --access-key=XXX --password=XXX status
```

**Comment by Salvora** [comment]
Okay, let me present what I found after trying a couple of things:
First of all, I have below values as shown for my device:
Serial: *** *** ***
Access: **** **** **** ****
Password: ********

I installed the command line tool and tried to get the status with below command.
`easy --serial=********* --access-key=**************** --password=******** status`

but it just hangs there.
I tried writing as shown on the device like this.
`easy --serial=*** *** *** --access-key=**** **** **** **** --password=******** status`
but it just showed me the main menu like below.
```
Usage:
  easy [options] status
  easy [options] pressure
  easy [options] location
  easy [options] active-program
  easy [options] program-data
  easy [options] display-code
  easy [options] supply-temperature
  easy [options] user-mode [ clock | manual ]
  easy [options] gas-usage [<page> | "?"]
  easy [options] hot-water-supply [ on | off ]
  easy [options] get <uri>
  easy [options] put <uri> <data>
  easy [options] set temperature <value>
  easy [options] set active-program <value>
  easy [options] decrypt [--type=TYPE] <base64>
```
I tried with debug as you suggested but it gives the same output no matter what input I use.
```
 xmpp:client:session start socket connection +0ms
  xmpp:connection setup socket +0ms
  xmpp:connection use lazy socket +3ms
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +204ms
  xmpp:connection receive: <?xml version='1.0' encoding='UTF-8'?><stream:stream xmlns:stream="http://etherx.jabber.org/streams" xmlns="jabber:client" from="wa2-mz36-qrmzh6.bosch.de" id="yokszd860" xml:lang="en" version="1.0"> +74ms
  xmpp:connection receive: <stream:features><starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"></starttls><mechanisms xmlns="urn:ietf:params:xml:ns:xmpp-sasl"><mechanism>PLAIN</mechanism><mechanism>SCRAM-SHA-1</mechanism><mechanism>DIGEST-MD5</mechanism></mechanisms><ver xmlns="urn:xmpp:features:rosterver"/></stream:features> +73ms
  xmpp:connection send: <starttls xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +2ms
  xmpp:connection receive: <proceed xmlns="urn:ietf:params:xml:ns:xmpp-tls"/> +74ms
  xmpp:connection use standard socket +8ms
  xmpp:connection setup stream +0ms
  xmpp:connection use lazy socket +1s
  xmpp:connection setup stream +1ms
  xmpp:connection send: <stream:stream xmlns="jabber:client" xmlns:stream="http://etherx.jabber.org/streams" version="1.0" to="wa2-mz36-qrmzh6.bosch.de"> +128ms
```
What do I do now?

**Comment by robertklep** [comment]
When there are spaces in values, you need to enclose them with quote characters. So if your serial number is `123 456`, you need to use it like this:
```
easy --serial='123 456'
```
(and similar for the other credentials)

I forgot that your problem may be also be caused by (semi-)recent OpenSSL configuration changes on Linux. See here: https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions

**Comment by Salvora** [comment]
> 
> 
> When there are spaces in values, you need to enclose them with quote characters. So if your serial number is `123 456`, you need to use it like this:
> 
> ```
> easy --serial='123 456'
> ```
> 
> (and similar for the other credentials)
> 
> I forgot that your problem may be also be caused by (semi-)recent OpenSSL configuration changes on Linux. See here: https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions

Yep, exactly as you have described.
Once I fixed the OpenSSL.conf, the problem is gone. 
Thanks for that.

**Comment by Kevin-com** [comment]
Hello. I too would like to connect my TC100 to Homebridge, without success. I would like to make the adjustment in the openssl.cnf file but get the message that I do not have access when I want to save it. Does anyone have an idea what the problem could be? Thank you.

Sorry for me bad English. :-)

**Comment by robertklep** [comment]
@Kevin-com if you want to edit system files, you need to do that with superuser ("root") privileges:
```
sudo $EDITOR /etc/openssl.cnf
```

**Comment by Kevin-com** [comment]
> @Kevin-com if you want to edit system files, you need to do that with superuser ("root") privileges:
> 
> ```
> sudo $EDITOR /etc/openssl.cnf
> ```

Thank you for your answer. I’m trying but get the message that this command is not allowed. Sorry, pretty new to this.

**Comment by robertklep** [comment]
@Kevin-com what kind of hardware and Linux distribution are you using?

**Comment by Kevin-com** [comment]
> @Kevin-com what kind of hardware and Linux distribution are you using?

Raspberry... Suddenly it works. I think I forgot to log in as 'root'. Later in the day I will try to connect the TC100. Thank you for your help.

**Comment by Kevin-com** [comment]
@robertklep, everything is working now. Thank you for your help and this great tool. Have a nice day!

**Comment by robertklep** [comment]
@Kevin-com you too, have fun!

**Comment by claessensbrent** [comment]
@Salvora @robertklep @Kevin-com 
Is it still working for the Buderuc TC100? I am trying to get it set up through Hoobs but keep getting errors.

I am quite sure about my config:

{
    "accessories": [
        {
            "accessory": "NefitEasy",
            "name": "Thermostaat",
            "options": {
                "serialNumber": "xxx xxx xxx",
                "accessKey": "xxxx xxxx xxxx xxxx",
                "password": "xxxxxxxxx"
            },
            "plugin_map": {
                "plugin_name": "homebridge-nefit-easy"
            }
        }
    ]
}

Read about the Linux issue but that doesn't make sense to me (I am quite new to this with little or none IT background...)

This is my log:
6-9-2021 17:44:11Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:44:11Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:44:11Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:45:03Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:45:03Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:45:03Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:46:33Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:46:33Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:46:33Nefit Easy BridgeERRORXMPP authentication failure
6-9-2021 17:46:41Nefit Easy BridgeERRORError [ERR_UNHANDLED_ERROR]: Unhandled error. ('XMPP authentication failure')
    at Client.emit (events.js:389:17)
    at Client.emit (domain.js:470:12)
    at Client._handleAuthState (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-client/lib/Client.js:295:10)
    at Client._handleStanza (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-client/lib/Client.js:233:12)
    at Client.onStanza (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at Connection.emit (events.js:400:28)
    at Connection.emit (domain.js:470:12)
    at Connection.onStanza (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at StreamParser.emit (events.js:400:28)
    at StreamParser.emit (domain.js:470:12)
    at SaxLtx.<anonymous> (/var/lib/hoobs/nefiteasybridge/node_modules/@xmpp/streamparser/index.js:69:14)
    at SaxLtx.emit (events.js:400:28)
    at SaxLtx.emit (domain.js:470:12)
    at SaxLtx._handleTagOpening (/var/lib/hoobs/nefiteasybridge/node_modules/ltx/lib/parsers/ltx.js:40:12)
    at SaxLtx.write (/var/lib/hoobs/nefiteasybridge/node_modules/ltx/lib/parsers/ltx.js:159:18)
    at StreamParser.write (/var/lib/hoobs/nefiteasybridge/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)

Thank you all in advance for any help you are able to give me!

**Comment by Salvora** [comment]
@claessensbrent bosch changed the xmpp servers so that is probably why.

**Comment by robertklep** [comment]
@Salvora that's not the problem here, I can access my Easy just fine without having to use other servers. Besides, the only server that is supposed to be changing is one used by the CT200, and that server is still working fine.

@claessensbrent try removing all whitespace and hyphens from the serial number and access key properties.

**Comment by claessensbrent** [comment]
@robertklep Thank you!

However, that doesn't seem to fix it. Tried all possible combinations of with or without spaces and hyphens but no succes. I am now working without spaces and get following log:

6-9-2021 19:51:34Nefit Easy BridgeERRORError [ERR_UNHANDLED_ERROR]: Unhandled error. ('XMPP authentication failure')
    at Client.emit (events.js:389:17)
    at Client.emit (domain.js:470:12)
    at Client._handleAuthState (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-client/lib/Client.js:295:10)
    at Client._handleStanza (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-client/lib/Client.js:233:12)
    at Client.onStanza (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at Connection.emit (events.js:400:28)
    at Connection.emit (domain.js:470:12)
    at Connection.onStanza (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at StreamParser.emit (events.js:400:28)
    at StreamParser.emit (domain.js:470:12)
    at SaxLtx.<anonymous> (/var/lib/hoobs/nefiteasybridge/node_modules/@xmpp/streamparser/index.js:69:14)
    at SaxLtx.emit (events.js:400:28)
    at SaxLtx.emit (domain.js:470:12)
    at SaxLtx._handleTagOpening (/var/lib/hoobs/nefiteasybridge/node_modules/ltx/lib/parsers/ltx.js:40:12)
    at SaxLtx.write (/var/lib/hoobs/nefiteasybridge/node_modules/ltx/lib/parsers/ltx.js:159:18)
    at StreamParser.write (/var/lib/hoobs/nefiteasybridge/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/var/lib/hoobs/nefiteasybridge/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at TLSSocket.emit (events.js:412:35)
    at TLSSocket.emit (domain.js:470:12)
    at addChunk (internal/streams/readable.js:290:12)
    at readableAddChunk (internal/streams/readable.js:265:9)

Looks the same as before...

**Comment by robertklep** [comment]
I never had, or tested with, a TC100 so I don't know if it requires something specific. For testing purposes, [this tool](https://github.com/robertklep/nefit-easy-cli) can provide more information on where it's failing, but you need to be able to install and run it.
