### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by DiederikDeConinck** [robertklep/homebridge-nefit-easy#3]
Hi,

Thanks for this great project! 
Unfortunately I can't use it yet. What is wrong?

root@raspberrypi:/usr/lib/node_modules/homebridge# homebridge
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[11/9/2016, 12:43:08 AM] Loaded plugin: homebridge-nefit-easy
[11/9/2016, 12:43:08 AM] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[11/9/2016, 12:43:08 AM] ---
[11/9/2016, 12:43:08 AM] Loaded config.json with 1 accessories and 0 platforms.
[11/9/2016, 12:43:08 AM] ---
[11/9/2016, 12:43:08 AM] Loading 1 accessories...
[11/9/2016, 12:43:08 AM] [Thermostaat] Initializing NefitEasy accessory...
buffer.js:262
  throw new TypeError(kFromErrorMsg);
  ^

TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.
    at fromObject (buffer.js:262:9)
    at Function.Buffer.from (buffer.js:101:10)
    at new Buffer (buffer.js:80:17)
    at generateKey (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/encryption.js:9:26)
    at new Encryption (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/encryption.js:16:14)
    at Encryption (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/encryption.js:15:46)
    at NefitEasyClient (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:40:21)
    at new NefitEasyClient (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-commands/lib/index.js:9:17)
    at NefitEasyClient (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-commands/lib/index.js:7:12)
    at new NefitEasyAccessory (/usr/lib/node_modules/homebridge-nefit-easy/index.js:14:18)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:262:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:78:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

Thanks!

**Comment by robertklep** [comment]
Hi Diederik!

My guess is that this is caused by an incomplete/incorrect configuration of the credentials. Do you have something similar to [this](https://github.com/robertklep/homebridge-nefit-easy#configuration) in your Homebridge configuration file?

**Comment by DiederikDeConinck** [comment]
Hi!

Thanks for your fast reply! 
Here's my configuration file:
{
        "bridge": {
                "name": "Homebridge",
                "username": "CC:22:3D:E3:CE:30",
                "port": 51826,
                "pin": "031-45-154"
        },

        "accessories": [{
                "accessory": "NefitEasy",
                "name": "Thermostaat",
                "options": {
                        "serialNumber": "619XXXXXX",
                        "accesKey": "SEt2gQvdXXXXXXXX",
                        "password": "password"
                }
        }]
}
Kind regards

**Comment by robertklep** [comment]
Ah, `accessKey` is misspelled (it misses an `s`).

I'm updating the plugin so it'll show you a proper warning when any of the credentials are missing, instead of it just crashing :)

**Comment by DiederikDeConinck** [comment]
Oh okay! My fault :p Thanks I'll give it a try.

**Comment by DiederikDeConinck** [comment]
I'm having another error right now:
[11/9/2016, 7:57:56 AM] Homebridge is running on port 51826.
[11/9/2016, 7:58:38 AM] [Thermostaat] Getting current temperature...
[11/9/2016, 7:58:38 AM] [Thermostaat] Getting target temperature...
[11/9/2016, 7:58:38 AM] [Thermostaat] Getting current state..
SyntaxError: Unexpected token � in JSON at position 0
    at Object.parse (native)
    at pending.(anonymous function).send.then.e (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:222:28)
    at tryCatcher (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues (/usr/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:637:20)
    at tryOnImmediate (timers.js:610:5)
    at processImmediate [as _immediateCallback] (timers.js:582:5)

I already made a totally new file and I wrote everything again in the config.json but I'm still getting this. What can I do about this? 
Kind regards

**Comment by robertklep** [comment]
It means that the data can't be decrypted, which generally would be caused by invalid credentials (incorrect password or access key).

The [standalone CLI tool](https://github.com/robertklep/nefit-easy-cli) might be easier to debug this with, as you can more easily pass credentials and don't need to start Homebridge every time you changed the config.

**Comment by DiederikDeConinck** [comment]
Alright that fixed it! Thanks for your help 😊

**Comment by robertklep** [comment]
FWIW, I pushed v1.2.0 that should give more legible error messages when credentials are missing or invalid :)
