### ISSUE TITLE
Error: MAX_RETRIES_REACHED

### ISSUE THREAD

**Issue by GuitarHer01** [robertklep/homebridge-nefit-easy#32]
The Homebridge Nefit Easy plugin give me this error several times every day now. 
All other Homebridge devices are also disconnected after this error. (not responding in Homekit) 
Sometimes the devices are reachable again after some time, sometimes the server has to be restarted to solve this. 

Can you pls look in to this?

_

> Error: MAX_RETRIES_REACHED
>     at C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\nefit-easy-core\lib\index.js:179:51
>     at tryCatcher (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\util.js:16:23)
>     at Promise._settlePromiseFromHandler (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\promise.js:547:31)
>     at Promise._settlePromise (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\promise.js:604:18)
>     at Promise._settlePromise0 (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\promise.js:649:10)
>     at Promise._settlePromises (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\promise.js:725:18)
>     at _drainQueueStep (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\async.js:93:12)
>     at _drainQueue (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\async.js:86:9)
>     at Async._drainQueues (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\async.js:102:5)
>     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Install\AppData\Roaming\npm\node_modules\homebridge-nefit-easy\node_modules\bluebird\js\release\async.js:15:14)
>     at processImmediate (internal/timers.js:461:21)
> Error: MAX_RETRIES_REACHED

_

**Comment by robertklep** [comment]
There's not much to look into: when the plugin doesn't get a response to a query within 2 seconds, it starts retrying. If after 15 retries it still hasn't gotten a response, it throws that error.

This issue is ultimately one that is beyond the plugin's control: either your internet connection has issues, or the Bosch/Nefit backend has issues.

**Comment by GuitarHer01** [comment]
I am using the internet normally at the time the problem occurs, so no problem with the internet connection.
Problaby some issues with the backend than, but why are all other Homebridge devices unavailable during this error? (Homebridge camera's, Homebridge Sonos, etc)
The Homebridge UI X and server are fully reachable and show no sign of errors other than the Nefit Easy MAX_RETRIES_REACHED . 
After this error is gone,  all Homebridge devices are responding again.

**Comment by robertklep** [comment]
I don't know about the internals of Homebridge, so perhaps it doesn't like it when plugins throw exceptions. However, it _is_ an exceptional situation, so the issue would probably be solved by finding out why the connection to your Nefit is failing.

You can install the [Nefit CLI tool](https://github.com/robertklep/nefit-easy-cli) and run it whenever the plugin fails (preferably from the same machine that Homebridge is running on) to see if that sheds any light on what's going on. You can enable debugging to make it produce debugging info:
```
$ env DEBUG=* easy --serial=XXX --access-key=XXX --password=XXX status
```
