### ISSUE TITLE
Error: POSSIBLE_INVALID_PASSWORD

### ISSUE THREAD

**Issue by wilkovb** [robertklep/homebridge-nefit-easy#38]
Hi,

I got a strange thing, i reinstalled my homebridge completly in order to make use of the latest version with the Gui of homebridge.

Installed everything 2 weeks ago without any problems, but i used a sd card of 128GB, which does not make sense.

So today i installed it again using my old 32GB sd card with the latest build 22-02-2022 of the Homebridge image.

This time i did get the below error in the logs.

[homebridge-nefit-easy] This plugin slows down Homebridge. The read handler for the characteristic 'Target Temperature' was slow to respond! See https://git.io/JtMGR for more info.
Error: POSSIBLE_INVALID_PASSWORD
    at /usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/nefit-easy-core/lib/index.js:218:19
    at tryCatcher (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:466:21)
    at processImmediate (node:internal/timers:466:21)

And now it does not work anymore.

You would guess that the password in it is wrong. But i had a copy of the config.json file of the build wich worked before, and used the exact same entries.

I also edited the openssl.cnf file with the option to use the old ssl version (which was not set on the previous working build and did work without it) 

Maybe i missed something?

Thanks in advance!
Wilko

**Comment by wilkovb** [comment]
yes it works again!

thanks!

**Comment by robertklep** [comment]
Apologies for the inconvenience 🥴
