### ISSUE TITLE
Buderus KM100 can't connect

### ISSUE THREAD

**Issue by scholli113** [robertklep/homebridge-nefit-easy#41]
HI,

I have a Buderus KM100, as I understand Nefit would be the protocol that should work but what ever I try I can't seem to looking. I tried Variations for logging in. 

I tried like this

"accessories": [
        {
            "accessory": "NefitEasy",
            "name": "thermostaat",
            "options": {
                "serialNumber": "XXX XXX XXX",
                "accessKey": "XXX-XXX-XXX-XXX",
                "password": "Bosch ID PW also tried Device PW"
            }
        }
    ],

I tried like this

"accessories": [
        {
            "accessory": "NefitEasy",
            "name": "thermostaat",
            "options": {
                "serialNumber": "XXXXXXXXX",
                "accessKey": "XXXXXXXXXXXX",
                "password": "Bosch ID PW also tried Device PW"
            }
        }
    ],

Would be great If somebody can give me some ideas what to do here

**Comment by robertklep** [comment]
Which error are you receiving, specifically? I can't remember if the KM100 uses the same protocol as the Easy.

**Comment by scholli113** [comment]
I get this message

Error: Unhandled error. ('XMPP authentication failure')
    at new NodeError (node:internal/errors:372:5)
    at Client.emit (node:events:516:17)
    at Client._handleAuthState (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/node-xmpp-client/lib/Client.js:295:10)
    at Client._handleStanza (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/node-xmpp-client/lib/Client.js:233:12)
    at Client.onStanza (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/node-xmpp-client/lib/Client.js:221:8)
    at Connection.emit (node:events:527:28)
    at Connection.onStanza (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/node-xmpp-core/lib/Connection.js:377:10)
    at StreamParser.<anonymous> (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/node-xmpp-core/lib/Connection.js:231:10)
    at StreamParser.emit (node:events:527:28)
    at SaxLtx.<anonymous> (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/@xmpp/streamparser/index.js:69:14)
    at SaxLtx.emit (node:events:527:28)
    at SaxLtx._handleTagOpening (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/ltx/lib/parsers/ltx.js:40:12)
    at SaxLtx.write (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/ltx/lib/parsers/ltx.js:159:18)
    at StreamParser.write (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/@xmpp/streamparser/index.js:134:17)
    at Connection.onData (/usr/local/lib/node_modules/homebridge-nefit-easy/node_modules/node-xmpp-core/lib/Connection.js:310:17)
    at TLSSocket.emit (node:events:539:35)

**Comment by scholli113** [comment]
Its hard for me to understand how the set serial, Accesskey, and password

Or is KM100 is supported at all

**Comment by robertklep** [comment]
XMPP authentication relies on the serial number and access key, not the password.

For Nefit, the serial number consists of 9 digits and the access key of 16 characters (without any hyphens, `-`, in between), and is also case-sensitive (so a lower case "a" is not considered to be the same as an upper case "A").

Both values can be found on the packaging of the device, and/or on the device itself.

I also don't know if the KM100 is supported, at least by the Nefit Easy driver. There's also a more generic module, [`bosch-xmpp`](https://github.com/robertklep/bosch-xmpp/) which (I believe) _does_ support it, but there's not HomeBridge support for it.

**Comment by scholli113** [comment]
Okay I guess it doesn't to I get this correct for bosch-xmpp I would need to setup home assistant which I then can connect to HomeKit
