### ISSUE TITLE
help me...

### ISSUE THREAD

**Issue by ZoltXs** [robertklep/homebridge-nefit-easy#5]
hello, I'm trying to install plugin and when I run homebridge it tells me that I have to register accessory at http://jsonlint.com and validate config.json file.
pi@raspberrypi:~/.homebridge $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[2017-11-4 19:00:34] Loaded plugin: homebridge-nefit-easy
[2017-11-4 19:00:34] Registering accessory 'homebridge-nefit-easy.NefitEasy'
[2017-11-4 19:00:34] ---
[2017-11-4 19:00:34] There was a problem reading your config.json file.
[2017-11-4 19:00:34] Please try pasting your config.json file here to validate it: http://jsonlint.com
[2017-11-4 19:00:34] 
/usr/lib/node_modules/homebridge/lib/server.js:206
    throw err;
    ^

SyntaxError: Unexpected token . in JSON at position 259
    at JSON.parse (<anonymous>)
    at Server._loadConfig (/usr/lib/node_modules/homebridge/lib/server.js:200:19)
    at new Server (/usr/lib/node_modules/homebridge/lib/server.js:57:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by robertklep** [comment]
Please add the contents of `config.json` to your question so I can take a look at it.

**Comment by ZoltXs** [comment]
{
    "bridge": {
        "name": "HomeNoXs",
        "username": "CC:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-154"
    },
    
    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for cre$

    "accessories": [
    ...
    {
        "accessory" : "NefitEasy",
        "name"      : "termostato",
        "options"   : {
            "serialNumber" : "660908XXX",
            "accessKey"    : "KTLVBPB32Pc3vXXX",
            "password"     : "8810"
        }
    }
] ,

    "platforms": []
}

**Comment by robertklep** [comment]
@ZoltXs try this:

```
{
  "bridge": {
    "name": "HomeNoXs",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-154"
  },
  "description": "My House",
  "accessories": [
    {
      "accessory": "NefitEasy",
      "name": "termostato",
      "options": {
        "serialNumber": "660908XXX",
        "accessKey": "AAA",
        "password": "BBB"
      }
    }
  ]
}
```

(I edited out the `accessKey` and `password` from your comment, I'm not sure if their values were the actual values you use or not, but this is a public website so anyone can see what you write)

**Comment by ZoltXs** [comment]
If I publish my values, anyone can access

**Comment by ZoltXs** [comment]
Thank you very much for everything, working correctly. good job
